[package]
name = "tree2svg"
version = "0.1.0"
authors = ["Simon Penel <simon.penel@univ-lyon1.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
taxonomy = "0.7.0"
svg = "0.8.1"
log = "0.4.14"
env_logger = "0.8.3"
structopt = "0.3"
